<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.JellyArrCleaner</RootNamespace>
    <AssemblyName>Jellyfin.Plugin.JellyArrCleaner</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.*" />
    <PackageReference Include="Jellyfin.Model" Version="10.11.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\PluginConfigurationPage.html" />
  </ItemGroup>

</Project>